"""Fluent adapter.

- log / transcript (output of `mesh/check` and `mesh/quality`): parsed directly.
- .cas / .msh (+ .h5): if `fluent` is on PATH, run it in batch with a journal;
  otherwise write the journal for the user and, for ASCII .msh, fall back to the
  generic (meshio + VTK) route so there is still something to report.
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess

from common import finding, grade

NUM = r"([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)"

ADVICE = {
    "negative_volume": [
        "负体积单元会使 Fluent 无法初始化或在第一步报错，必须先在网格软件中修复。",
        "动网格算例中若运动后才出现负体积，属于网格变形问题：检查 smoothing/remeshing 设置、时间步和运动边界附近的网格余量。",
    ],
    "orthogonal_quality": [
        "定位最差单元所在的 zone（报告中给出了 zone 编号和坐标），优先在网格软件中局部修复或重划分。",
        "Fluent 中可尝试 Mesh > Improve Quality（mesh/repair-improve/improve-quality），对多面体网格效果较好。",
        "暂时无法改网格时：先用一阶迎风格式和较小松弛因子起算，稳定后再切换高阶格式。",
    ],
    "skewness": [
        "高歪斜单元通常出现在几何尖角、薄缝和边界层与核心网格的过渡处，检查报告中最差单元的位置。",
        "四面体网格可考虑转为多面体网格（Fluent: mesh/polyhedra/convert-domain），通常能显著降低歪斜度。",
    ],
    "aspect_ratio": [
        "若大长宽比单元位于边界层，一般是有意为之；若位于主流区，应调整网格尺寸控制。",
        "大长宽比配合双精度求解器（3ddp/2ddp）更稳妥。",
    ],
}

JOURNAL = """; Fluent batch journal generated by mesh-quality-check
; Usage: fluent {dim}ddp -g -t1 -i {jou}
/file/start-transcript "{trn}"
/file/read-case "{case}"
/mesh/check
/mesh/quality
/file/stop-transcript
/exit yes
"""


def parse_fluent(text: str) -> dict:
    g = {"quality": [], "volume": {}, "area": {}, "extents": {}, "warnings": [], "errors": []}

    for m in re.finditer(r"^\s*(Minimum|Maximum)\s+([A-Za-z][A-Za-z \-]*?)\s*[=:]\s*" + NUM + r"(.*)$", text, re.M):
        stat, name, val, rest = m.group(1).lower(), m.group(2).strip(), float(m.group(3)), m.group(4)
        item = {"stat": stat, "name": name, "value": val, "line": m.group(0).strip()}
        z = re.search(r"on zone\s+(\d+)", rest)
        c = re.search(r"cell\s+(\d+)", rest)
        loc = re.search(r"at location\s*\(([^)]*)\)", rest)
        if z:
            item["zone"] = int(z.group(1))
        if c:
            item["cell"] = int(c.group(1))
        if loc:
            item["xyz"] = [float(x) for x in re.findall(NUM, loc.group(1))]
        g["quality"].append(item)

    for key, pat in (("min", r"minimum volume \(m3\)\s*:\s*" + NUM), ("max", r"maximum volume \(m3\)\s*:\s*" + NUM),
                     ("total", r"total volume \(m3\)\s*:\s*" + NUM)):
        m = re.search(pat, text, re.I)
        if m:
            g["volume"][key] = float(m.group(1))
    for key, pat in (("min", r"minimum (?:face )?area \(m2\)\s*:\s*" + NUM), ("max", r"maximum (?:face )?area \(m2\)\s*:\s*" + NUM)):
        m = re.search(pat, text, re.I)
        if m:
            g["area"][key] = float(m.group(1))
    for ax in "xyz":
        m = re.search(ax + r"-coordinate:\s*min \(m\)\s*=\s*" + NUM + r",\s*max \(m\)\s*=\s*" + NUM, text, re.I)
        if m:
            g["extents"][ax] = [float(m.group(1)), float(m.group(2))]
    m = re.search(r"^\s*0\s+(\d+)\s+(\d+)\s+(\d+)\s+\d+\s*$", text, re.M)  # 'Level Cells Faces Nodes Partitions' table
    if m:
        g["n_cells"], g["n_faces"], g["n_nodes"] = int(m.group(1)), int(m.group(2)), int(m.group(3))
    for line in text.splitlines():
        s = line.strip()
        if re.match(r"(warning|warn)\b", s, re.I):
            g["warnings"].append(s)
        elif re.match(r"error\b", s, re.I) or "negative volume" in s.lower():
            g["errors"].append(s)
    return g


def _metric_of(name: str):
    n = name.lower()
    if "orthogonal quality" in n:
        return "orthogonal_quality", "正交质量（Fluent 定义）"
    if "skew" in n:
        return "skewness", "歪斜度（Fluent 定义）"
    if "aspect" in n:
        return "aspect_ratio", "长宽比"
    return None, None


def _from_parsed(g, det, limits):
    findings = []
    info = {}
    if g.get("n_cells"):
        info["n_cells"] = g["n_cells"]
        info["n_faces"] = g.get("n_faces")
    if g["extents"]:
        info["bounds"] = [[g["extents"][a][0] for a in "xyz" if a in g["extents"]],
                          [g["extents"][a][1] for a in "xyz" if a in g["extents"]]]
        info["n_dims"] = len(g["extents"])
    if g["volume"]:
        info["cell_volume"] = g["volume"]

    vmin = g["volume"].get("min")
    neg_lines = [l for l in g["errors"] if "negative" in l.lower()]
    if (vmin is not None and vmin <= 0) or neg_lines:
        findings.append(finding("negative_volume", "负体积/零体积单元", category="critical", value=vmin, stat="min",
                                severity="critical", raw=(neg_lines or [None])[0], advice=ADVICE["negative_volume"]))

    seen = set()
    for q in g["quality"]:
        metric, zh = _metric_of(q["name"])
        if not metric or metric in seen:
            continue
        seen.add(metric)
        sev = grade("fluent", metric, q["value"])
        loc = None
        if "zone" in q or "xyz" in q:
            loc = {"worst": [{"id": q.get("cell"), "zone": q.get("zone"), "xyz": q.get("xyz"), "value": q["value"]}]}
        findings.append(finding(metric, zh, value=q["value"], stat=q["stat"], source="fluent", severity=sev,
                                location=loc, raw=q["line"],
                                definition={"orthogonal_quality": "0–1，1 为理想，越小越差",
                                            "skewness": "0–1，0 为理想，越大越差",
                                            "aspect_ratio": "1 为理想"}[metric],
                                advice=ADVICE.get(metric, []) if sev != "ok" else []))
    if g["quality"]:
        limits.append("Fluent 的 mesh/quality 只输出极值和最差单元位置，不给出超标单元数量和分布；"
                      "如需判断影响范围，可在 Fluent 中查看 Orthogonal Quality 等值线或直方图，"
                      "或把网格导出为 CGNS/ASCII .msh 后用本工具的通用路线统计。")
    else:
        limits.append("日志中没有 mesh/quality 输出（只有 mesh/check），缺少正交质量和歪斜度。请在 Fluent 中执行 mesh/quality 并提供输出。")
    return info, findings


def check(det: dict, log, out_dir: str) -> dict:
    limits, extra = [], {}
    path = det["path"]

    if det["kind"] == "log":
        log.add(f"读取 Fluent 日志/transcript：{path}")
        with open(path, encoding="utf-8", errors="replace") as f:
            g = parse_fluent(f.read())
        info, findings = _from_parsed(g, det, limits)
        extra["warnings"] = g["warnings"]
        extra["errors"] = g["errors"]
        return {"source": "fluent", "input_kind": "log", "mesh_info": info, "findings": findings,
                "extra": extra, "limitations": limits}

    # case/mesh file
    jou = os.path.join(out_dir, "fluent_mesh_check.jou")
    trn = os.path.join(out_dir, "fluent_mesh_check.trn")
    dim = "3"
    with open(jou, "w", encoding="utf-8") as f:
        f.write(JOURNAL.format(dim=dim, jou=jou, trn=trn, case=path.replace("\\", "/")))
    log.add(f"已生成 Fluent 批处理 journal：{jou}")

    exe = shutil.which("fluent")
    if exe:
        cmd = [exe, f"{dim}ddp", "-g", "-t1", "-i", jou]
        log.add("以批处理模式运行 Fluent", cmd=" ".join(cmd))
        try:
            subprocess.run(cmd, capture_output=True, text=True, timeout=3600, cwd=out_dir)
        except Exception as e:  # noqa: BLE001
            log.add(f"Fluent 运行失败：{e}", status="error")
        if os.path.exists(trn):
            with open(trn, encoding="utf-8", errors="replace") as f:
                g = parse_fluent(f.read())
            info, findings = _from_parsed(g, det, limits)
            extra.update(warnings=g["warnings"], errors=g["errors"])
            return {"source": "fluent", "input_kind": det["kind"], "mesh_info": info, "findings": findings,
                    "extra": extra, "limitations": limits}

    log.add("未找到 fluent 可执行文件，无法直接运行 Fluent 检查", status="skip")
    limits.append(f"本机没有 Fluent。可在装有 Fluent 的机器上运行：`fluent 3ddp -g -t1 -i fluent_mesh_check.jou`"
                  f"（二维网格改为 2ddp），再把生成的 fluent_mesh_check.trn 交给本工具。journal 已放在报告目录。")

    if det["kind"] == "mesh":
        log.add("尝试用通用路线（meshio）读取 Fluent .msh 作为补充")
        from adapters import generic
        res = generic.check(dict(det, source="generic"), log, out_dir)
        res["source"] = "fluent"
        res["route_note"] = "Fluent .msh 通过 meshio 读取，用 VTK 指标评估（非 Fluent 原生指标，数值不可与 Fluent 报告直接比较）"
        res["limitations"] = limits + res.get("limitations", [])
        res.setdefault("extra", {})["journal"] = jou
        return res

    return {"source": "fluent", "input_kind": det["kind"], "mesh_info": {}, "findings": [],
            "extra": {"journal": jou}, "limitations": limits + ["Fluent .cas 为专有格式，本工具无法直接读取网格。"]}
